#!/usr/bin/env bash
# Generate LVGL v9 C fonts from fonts/*.ttf into generated/.
# Uses lv_font_conv 1.5.3 (npx). Output is deterministic for a given tool version.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FONTS="$ROOT/fonts"
GEN="$ROOT/generated"
CONV_PKG="lv_font_conv@1.5.3"

if ! command -v npx >/dev/null 2>&1; then
  # shellcheck disable=SC1090
  source "${HOME}/.nvm/nvm.sh"
fi

mkdir -p "$GEN"
cd "$ROOT"

CONV=(npx --yes "$CONV_PKG")
CONV_VER="$("${CONV[@]}" -v 2>/dev/null | tail -n 1)"
CONV_VER="${CONV_VER:-1.5.3}"

ASCII_RANGE="0x20-0x7E,0xB7,0x2013,0x2026"
# space, hyphen-minus, digits 0-9, colon
TIMER_RANGE="0x20,0x2D,0x30-0x3A"

gen_one() {
  local ttf="$1" name="$2" size="$3"
  shift 3
  local rel="generated/${name}.c"
  echo "font ${name} size=${size}"
  "${CONV[@]}" \
    --bpp 4 \
    --no-compress \
    --no-prefilter \
    --format lvgl \
    --lv-include lvgl.h \
    --lv-font-name "$name" \
    --font "$ttf" \
    --size "$size" \
    "$@" \
    -o "$rel"
  local tmp
  tmp="$(mktemp)"
  {
    echo "/* Generated by lv_font_conv ${CONV_VER}; do not edit. */"
    cat "$rel"
  } >"$tmp"
  chmod 644 "$tmp"
  mv "$tmp" "$rel"
}

# sb: Barlow Semi Condensed SemiBold
for s in 26 28; do
  gen_one "fonts/BarlowSemiCondensed-SemiBold.ttf" "zk_font_sb_${s}" "$s" --range "$ASCII_RANGE"
done

# b: Bold
for s in 26 28 34; do
  gen_one "fonts/BarlowSemiCondensed-Bold.ttf" "zk_font_b_${s}" "$s" --range "$ASCII_RANGE"
done

# xb: ExtraBold (full ASCII + extras)
for s in 28 32 36 40 42 44 48 50 58; do
  gen_one "fonts/BarlowSemiCondensed-ExtraBold.ttf" "zk_font_xb_${s}" "$s" --range "$ASCII_RANGE"
done

# xb 96 / 104: STOP word on the rail button
for s in 96 104; do
  gen_one "fonts/BarlowSemiCondensed-ExtraBold.ttf" "zk_font_xb_${s}" "$s" --symbols STOP
done

# xb 172: running-screen countdown (digits, colon, space, hyphen)
gen_one "fonts/BarlowSemiCondensed-ExtraBold.ttf" "zk_font_xb_172" 172 --range "$TIMER_RANGE"

# alfa: brand wordmark
gen_one "fonts/AlfaSlabOne-Regular.ttf" "zk_font_alfa_26" 26 --range "$ASCII_RANGE"

HEADER="$GEN/zk_fonts.h"
{
  echo "/* Generated by tools/gen-fonts.sh using lv_font_conv ${CONV_VER}; do not edit. */"
  echo "#ifndef ZK_FONTS_H"
  echo "#define ZK_FONTS_H"
  echo
  echo "#ifdef __cplusplus"
  echo "extern \"C\" {"
  echo "#endif"
  echo
  echo "#ifdef LV_LVGL_H_INCLUDE_SIMPLE"
  echo "#include \"lvgl.h\""
  echo "#else"
  echo "#include \"lvgl.h\""
  echo "#endif"
  echo
  for name in \
    zk_font_sb_26 zk_font_sb_28 \
    zk_font_b_26 zk_font_b_28 zk_font_b_34 \
    zk_font_xb_28 zk_font_xb_32 zk_font_xb_36 zk_font_xb_40 \
    zk_font_xb_42 zk_font_xb_44 zk_font_xb_48 zk_font_xb_50 \
    zk_font_xb_58 zk_font_xb_96 zk_font_xb_104 zk_font_xb_172 \
    zk_font_alfa_26
  do
    echo "LV_FONT_DECLARE(${name});"
  done
  echo
  echo "#ifdef __cplusplus"
  echo "}"
  echo "#endif"
  echo
  echo "#endif /* ZK_FONTS_H */"
} >"$HEADER"

echo "wrote ${HEADER}"
