#!/usr/bin/env node
/**
 * Rasterize design SVG icons to LVGL v9 A8 image descriptors.
 * White-on-transparent, 2x supersample then box-filter downscale.
 * Recolor at runtime with lv_obj_set_style_image_recolor.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ICONS_JSON = path.join(__dirname, 'icons.json');
const OUT_DIR = path.join(ROOT, 'generated');

const PLAYWRIGHT_CORE = process.env.PLAYWRIGHT_CORE || '';
const CHROMIUM_PATH = process.env.CHROMIUM_PATH || '';

const ICON_SIZES = {
  stop_oct: [84],
  pause: [44],
  play: [44],
  back: [44],
  drop: [30],
  cloud: [36, 52, 64],
  pencil: [40],
  list: [52],
  sunrise: [52],
  inf: [52],
  mark: [44],
};

const SUPER = 2;

function prepareSvg(svg, px) {
  let s = String(svg).trim();
  s = s.replace(/\bcurrentColor\b/g, '#ffffff');
  if (!/<svg[^>]*\sxmlns=/.test(s)) {
    s = s.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
  }
  s = s.replace(/<svg\b([^>]*)>/, (_, attrs) => {
    const rest = attrs.replace(/\s(width|height)="[^"]*"/g, '');
    return `<svg width="${px}" height="${px}" style="color:#ffffff"${rest}>`;
  });
  return s;
}

function downscaleA8(rgba, w, h, scale) {
  const sw = w * scale;
  const out = Buffer.alloc(w * h);
  const n = scale * scale;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      let sum = 0;
      for (let dy = 0; dy < scale; dy++) {
        for (let dx = 0; dx < scale; dx++) {
          const si = ((y * scale + dy) * sw + (x * scale + dx)) * 4;
          const a = rgba[si + 3];
          const lum = Math.max(rgba[si], rgba[si + 1], rgba[si + 2]);
          sum += Math.round((a * lum) / 255);
        }
      }
      out[y * w + x] = Math.round(sum / n);
    }
  }
  return out;
}

function dumpBytes(buf) {
  const lines = [];
  for (let i = 0; i < buf.length; i += 12) {
    const slice = buf.subarray(i, Math.min(i + 12, buf.length));
    const hex = Array.from(slice, (b) => `0x${b.toString(16).padStart(2, '0')}`);
    const comma = i + 12 < buf.length ? ',' : '';
    lines.push(`    ${hex.join(', ')}${comma}`);
  }
  return lines.join('\n');
}

async function rasterize(page, svg, size) {
  const renderPx = size * SUPER;
  const svgSized = prepareSvg(svg, renderPx);
  const b64 = await page.evaluate(async ({ svgXml, px }) => {
    const canvas = document.createElement('canvas');
    canvas.width = px;
    canvas.height = px;
    const ctx = canvas.getContext('2d', { alpha: true, willReadFrequently: true });
    ctx.clearRect(0, 0, px, px);
    const blob = new Blob([svgXml], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    try {
      const img = new Image();
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = () => reject(new Error('SVG image failed to load'));
        img.src = url;
      });
      ctx.drawImage(img, 0, 0, px, px);
    } finally {
      URL.revokeObjectURL(url);
    }
    const { data } = ctx.getImageData(0, 0, px, px);
    let bin = '';
    const step = 0x8000;
    for (let i = 0; i < data.length; i += step) {
      bin += String.fromCharCode.apply(null, data.subarray(i, i + step));
    }
    return btoa(bin);
  }, { svgXml: svgSized, px: renderPx });
  const rgba = Buffer.from(b64, 'base64');
  if (rgba.length !== renderPx * renderPx * 4) {
    throw new Error(`unexpected raster size ${rgba.length} for ${size}px`);
  }
  const alpha = downscaleA8(rgba, size, size, SUPER);
  let nz = 0;
  for (let i = 0; i < alpha.length; i++) if (alpha[i]) nz++;
  if (nz < 8) {
    throw new Error(`raster for ${size}px icon is empty (${nz} nonzero)`);
  }
  return alpha;
}

function emitC(images) {
  const parts = [];
  parts.push('/* Generated by tools/gen-icons.js; do not edit. */');
  parts.push('#ifdef LV_LVGL_H_INCLUDE_SIMPLE');
  parts.push('#include "lvgl.h"');
  parts.push('#else');
  parts.push('#include "lvgl.h"');
  parts.push('#endif');
  parts.push('');
  parts.push('#ifndef LV_ATTRIBUTE_MEM_ALIGN');
  parts.push('#define LV_ATTRIBUTE_MEM_ALIGN');
  parts.push('#endif');
  parts.push('');

  for (const im of images) {
    const map = `${im.sym}_map`;
    parts.push(`#ifndef LV_ATTRIBUTE_IMAGE_${im.sym.toUpperCase()}`);
    parts.push(`#define LV_ATTRIBUTE_IMAGE_${im.sym.toUpperCase()}`);
    parts.push('#endif');
    parts.push('');
    parts.push(
      `const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMAGE_${im.sym.toUpperCase()} uint8_t ${map}[] = {`
    );
    parts.push(dumpBytes(im.alpha));
    parts.push('};');
    parts.push('');
    parts.push(`const lv_image_dsc_t ${im.sym} = {`);
    parts.push('    .header.magic = LV_IMAGE_HEADER_MAGIC,');
    parts.push('    .header.cf = LV_COLOR_FORMAT_A8,');
    parts.push('    .header.flags = 0,');
    parts.push(`    .header.w = ${im.size},`);
    parts.push(`    .header.h = ${im.size},`);
    parts.push(`    .header.stride = ${im.size},`);
    parts.push('    .header.reserved_2 = 0,');
    parts.push(`    .data_size = ${im.size * im.size},`);
    parts.push(`    .data = ${map},`);
    parts.push('    .reserved = NULL,');
    parts.push('};');
    parts.push('');
  }
  return parts.join('\n') + '\n';
}

function emitH(images) {
  const lines = [
    '/* Generated by tools/gen-icons.js; do not edit. */',
    '#ifndef ZK_ICONS_H',
    '#define ZK_ICONS_H',
    '',
    '#ifdef __cplusplus',
    'extern "C" {',
    '#endif',
    '',
    '#ifdef LV_LVGL_H_INCLUDE_SIMPLE',
    '#include "lvgl.h"',
    '#else',
    '#include "lvgl.h"',
    '#endif',
    '',
  ];
  for (const im of images) {
    lines.push(`LV_IMAGE_DECLARE(${im.sym});`);
  }
  lines.push('');
  lines.push('#ifdef __cplusplus');
  lines.push('}');
  lines.push('#endif');
  lines.push('');
  lines.push('#endif /* ZK_ICONS_H */');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const spec = JSON.parse(fs.readFileSync(ICONS_JSON, 'utf8'));
  for (const name of Object.keys(ICON_SIZES)) {
    if (!spec[name]) throw new Error(`missing SVG for ${name} in icons.json`);
  }

  if (!PLAYWRIGHT_CORE || !CHROMIUM_PATH) {
    throw new Error('Set PLAYWRIGHT_CORE and CHROMIUM_PATH');
  }
  const { chromium } = require(PLAYWRIGHT_CORE);
  if (!fs.existsSync(CHROMIUM_PATH)) {
    throw new Error('Chromium not found at CHROMIUM_PATH');
  }

  const browser = await chromium.launch({
    executablePath: CHROMIUM_PATH,
    headless: true,
    args: ['--no-sandbox', '--disable-gpu', '--hide-scrollbars'],
  });

  const images = [];
  try {
    const page = await browser.newPage({
      viewport: { width: 256, height: 256 },
      deviceScaleFactor: 1,
    });
    await page.goto('about:blank');

    const names = Object.keys(ICON_SIZES);
    for (const name of names) {
      for (const size of ICON_SIZES[name]) {
        const sym = `zk_icon_${name}_${size}`;
        process.stderr.write(`icon ${sym}\n`);
        const alpha = await rasterize(page, spec[name], size);
        images.push({ name, size, sym, alpha });
      }
    }
  } finally {
    await browser.close();
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'zk_icons.c'), emitC(images));
  fs.writeFileSync(path.join(OUT_DIR, 'zk_icons.h'), emitH(images));
  process.stderr.write(`wrote ${images.length} icons\n`);
}

main().catch((err) => {
  console.error(err && err.stack ? err.stack : err);
  process.exit(1);
});
